language: node_js
node_js:
  - lts/*
  - stable
install:
  - npm install -g standard elm@0.18 elm-test@0.18
  - elm-package install -y
  - pushd tests && elm-package install -y && popd
script:
  - standard src/**/*.js && elm-test
